hotels:
  path: /dashboard/hotels
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@index
  methods:
    - GET
  permission: HotelModule

hotels.sort:
  path: /dashboard/hotels/sort
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@sort
  methods:
    - GET
  permission: HotelModule

hotels.ajax:
  path: /dashboard/hotels/ajax
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@ajax
  methods:
    - POST
  permission: HotelModule

hotels.create:
  path: /dashboard/hotels/create
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@create
  methods:
    - GET
  permission: HotelModule.add

hotels.store:
  path: /dashboard/hotels/store
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@store
  methods:
    - POST
  permission: HotelModule.add

hotels.edit:
  path: /dashboard/hotels/{{hotel}}/edit
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@edit
  methods:
    - GET
  permission: HotelModule.edit

hotels.update:
  path: /dashboard/hotels/{{hotel}}
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@update
  methods:
    - PUT
    - PATCH
  permission: HotelModule.edit

hotels.destroy:
  path: /dashboard/hotels/{{hotel}}
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@destroy
  methods:
    - DELETE
  permission: HotelModule.delete

hotels.saveOrder:
  path: /dashboard/hotels/saveOrder
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@saveOrder
  methods:
    - POST
  permission: HotelModule.edit

apartments:
  path: /dashboard/hotels-apartments
  controller: Selene\Modules\HotelModule\Http\Controllers\ApartmentController@index
  methods:
    - GET
  permission: HotelModule

apartments.sort:
  path: /dashboard/hotels-apartments/sort
  controller: Selene\Modules\HotelModule\Http\Controllers\ApartmentController@sort
  methods:
    - GET
  permission: HotelModule

apartments.ajax:
  path: /dashboard/hotels-apartments/ajax
  controller: Selene\Modules\HotelModule\Http\Controllers\ApartmentController@ajax
  methods:
    - POST
  permission: HotelModule

apartments.create:
  path: /dashboard/hotels-apartments/create
  controller: Selene\Modules\HotelModule\Http\Controllers\ApartmentController@create
  methods:
    - GET
  permission: HotelModule.add

apartments.store:
  path: /dashboard/hotels-apartments/store
  controller: Selene\Modules\HotelModule\Http\Controllers\ApartmentController@store
  methods:
    - POST
  permission: HotelModule.add

apartments.edit:
  path: /dashboard/hotels-apartments/{{apartment}}/edit
  controller: Selene\Modules\HotelModule\Http\Controllers\ApartmentController@edit
  methods:
    - GET
  permission: HotelModule.edit

apartments.update:
  path: /dashboard/hotels-apartments/{{apartment}}
  controller: Selene\Modules\HotelModule\Http\Controllers\ApartmentController@update
  methods:
    - PUT
    - PATCH
  permission: HotelModule.edit

apartments.destroy:
  path: /dashboard/hotels-apartments/{{apartment}}
  controller: Selene\Modules\HotelModule\Http\Controllers\ApartmentController@destroy
  methods:
    - DELETE
  permission: HotelModule.delete

apartments.saveOrder:
  path: /dashboard/hotels-apartments/saveOrder
  controller: Selene\Modules\HotelModule\Http\Controllers\ApartmentController@saveOrder
  methods:
    - POST
  permission: HotelModule.edit

wellness:
  path: /dashboard/hotels-wellness
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@index
  methods:
    - GET
  permission: HotelModule

wellness.sort:
  path: /dashboard/hotels-wellness/sort
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@sort
  methods:
    - GET
  permission: HotelModule

wellness.ajax:
  path: /dashboard/hotels-wellness/ajax
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@ajax
  methods:
    - POST
  permission: HotelModule

wellness.create:
  path: /dashboard/hotels-wellness/create
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@create
  methods:
    - GET
  permission: HotelModule.add

wellness.store:
  path: /dashboard/hotels-wellness/store
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@store
  methods:
    - POST
  permission: HotelModule.add

wellness.edit:
  path: /dashboard/hotels-wellness/{{wellness}}/edit
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@edit
  methods:
    - GET
  permission: HotelModule.edit

wellness.update:
  path: /dashboard/hotels-wellness/{{wellness}}
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@update
  methods:
    - PUT
    - PATCH
  permission: HotelModule.edit

wellness.destroy:
  path: /dashboard/hotels-wellness/{{wellness}}
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@destroy
  methods:
    - DELETE
  permission: HotelModule.delete

wellness.saveOrder:
  path: /dashboard/hotels-wellness/saveOrder
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@saveOrder
  methods:
    - POST
  permission: HotelModule.edit

kitchen:
  path: /dashboard/hotels-kitchen
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenController@index
  methods:
    - GET
  permission: HotelModule

kitchen.sort:
  path: /dashboard/hotels-kitchen/sort
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenController@sort
  methods:
    - GET
  permission: HotelModule

kitchen.ajax:
  path: /dashboard/hotels-kitchen/ajax
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenController@ajax
  methods:
    - POST
  permission: HotelModule

kitchen.create:
  path: /dashboard/hotels-kitchen/create
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenController@create
  methods:
    - GET
  permission: HotelModule.add

kitchen.store:
  path: /dashboard/hotels-kitchen/store
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenController@store
  methods:
    - POST
  permission: HotelModule.add

kitchen.edit:
  path: /dashboard/hotels-kitchen/{{kitchen}}/edit
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenController@edit
  methods:
    - GET
  permission: HotelModule.edit

kitchen.update:
  path: /dashboard/hotels-kitchen/{{kitchen}}
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenController@update
  methods:
    - PUT
    - PATCH
  permission: HotelModule.edit

kitchen.destroy:
  path: /dashboard/hotels-kitchen/{{kitchen}}
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenController@destroy
  methods:
    - DELETE
  permission: HotelModule.delete

kitchen.saveOrder:
  path: /dashboard/hotels-kitchen/saveOrder
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenController@saveOrder
  methods:
    - POST
  permission: HotelModule.edit

kitchen.type:
  path: /dashboard/hotels-kitchen-type
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenTypeController@index
  methods:
    - GET
  permission: HotelModule

kitchen.type.ajax:
  path: /dashboard/hotels-kitchen-type/ajax
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenTypeController@ajax
  methods:
    - POST
  permission: HotelModule

kitchen.type.create:
  path: /dashboard/hotels-kitchen-type/create
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenTypeController@create
  methods:
    - GET
  permission: HotelModule.add

kitchen.type.store:
  path: /dashboard/hotels-kitchen-type/store
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenTypeController@store
  methods:
    - POST
  permission: HotelModule.add

kitchen.type.edit:
  path: /dashboard/hotels-kitchen-type/{{type}}/edit
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenTypeController@edit
  methods:
    - GET
  permission: HotelModule.edit

kitchen.type.update:
  path: /dashboard/hotels-kitchen-type/{{type}}
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenTypeController@update
  methods:
    - PUT
    - PATCH
  permission: HotelModule.edit

kitchen.type.destroy:
  path: /dashboard/hotels-kitchen-type/{{type}}
  controller: Selene\Modules\HotelModule\Http\Controllers\KitchenTypeController@destroy
  methods:
    - DELETE
  permission: HotelModule.delete
