hotels:
  path: /dashboard/hotels
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@index
  methods:
    - GET
  permission: HotelModule

hotels.sort:
  path: /dashboard/hotels/sort
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@sort
  methods:
    - GET
  permission: HotelModule

hotels.ajax:
  path: /dashboard/hotels/ajax
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@ajax
  methods:
    - POST
  permission: HotelModule

hotels.create:
  path: /dashboard/hotels/create
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@create
  methods:
    - GET
  permission: HotelModule.add

hotels.store:
  path: /dashboard/hotels/store
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@store
  methods:
    - POST
  permission: HotelModule.add

hotels.edit:
  path: /dashboard/hotels/{{hotel}}/edit
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@edit
  methods:
    - GET
  permission: HotelModule.edit

hotels.update:
  path: /dashboard/hotels/{{hotel}}
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@update
  methods:
    - PUT
    - PATCH
  permission: HotelModule.edit

hotels.destroy:
  path: /dashboard/hotels/{{hotel}}
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@destroy
  methods:
    - DELETE
  permission: HotelModule.delete

hotels.saveOrder:
  path: /dashboard/hotels/saveOrder
  controller: Selene\Modules\HotelModule\Http\Controllers\HotelController@saveOrder
  methods:
    - POST
  permission: HotelModule.edit

wellness:
  path: /dashboard/hotels-wellness
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@index
  methods:
    - GET
  permission: HotelModule

wellness.sort:
  path: /dashboard/hotels-wellness/sort
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@sort
  methods:
    - GET
  permission: HotelModule

wellness.ajax:
  path: /dashboard/hotels-wellness/ajax
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@ajax
  methods:
    - POST
  permission: HotelModule

wellness.create:
  path: /dashboard/hotels-wellness/create
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@create
  methods:
    - GET
  permission: HotelModule.add

wellness.store:
  path: /dashboard/hotels-wellness/store
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@store
  methods:
    - POST
  permission: HotelModule.add

wellness.edit:
  path: /dashboard/hotels-wellness/{{wellness}}/edit
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@edit
  methods:
    - GET
  permission: HotelModule.edit

wellness.update:
  path: /dashboard/hotels-wellness/{{wellness}}
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@update
  methods:
    - PUT
    - PATCH
  permission: HotelModule.edit

wellness.destroy:
  path: /dashboard/hotels-wellness/{{wellness}}
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@destroy
  methods:
    - DELETE
  permission: HotelModule.delete

wellness.saveOrder:
  path: /dashboard/hotels-wellness/saveOrder
  controller: Selene\Modules\HotelModule\Http\Controllers\WellnessController@saveOrder
  methods:
    - POST
  permission: HotelModule.edit
